export function buildUserPrompt(
  formatTemplate: string | null | undefined,
  repoUrl: string | null | undefined,
  projectType: string,
  projectFiles: string[],
  fullCode: string,
  existingReadme: string | null | undefined,
  options: {
    includeSetup?: boolean;
    includeContributionGuideLine?: boolean;
    includeApiDocs?: boolean;
    includeDiagrams?: boolean;
    linkedinUrl?: string;
    twitterUrl?: string;
    isIncremental?: boolean;
    modifiedFiles?: string[];
  } = {}
): string {
  return formatTemplate
    ? `
      STRICTLY USE THIS TEMPLATE STRUCTURE:
     """
     ${formatTemplate}
     """

     INJECT THESE PROJECT DETAILS:
     - Repo URL: ${repoUrl || "Not specified"}
     - Project Type: ${projectType}
     - Main Files: ${projectFiles.slice(0, 10).join(", ")}...
     - Code Sample: ${fullCode.substring(0, 1000)}...

     RULES:
     1. PRESERVE ALL TEMPLATE SECTIONS IN ORDER
     2. REPLACE CONTENT BUT KEEP STYLING
     3. ADD THIS BADGE AT BOTTOM:
        [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://www.npmjs.com/package/dokugen)`
    : existingReadme
      ? `You are updating an existing README.md file. Your task is to INTELLIGENTLY UPDATE only the auto-generated sections while PRESERVING all custom content added by the user.

       ## EXISTING README CONTENT:
       """
       ${existingReadme}
       """

       ${options.isIncremental === true ? `
       ## INCREMENTAL UPDATE INFORMATION:
       - This is an incremental update request. The codebase was previously scanned and a README generated.
       - The 'Code' section below ONLY contains code for files that have been modified or added since the last generation:
         ${options.modifiedFiles ? options.modifiedFiles.map(f => `- ${f}`).join('\n') : '(modified files list not specified)'}
       - All other files listed in the project files list are completely unchanged.
       - Use these modified/new files to update relevant sections (such as new/changed API endpoints, new features, or setup changes), but preserve all other parts of the existing README as-is.
       ` : ''}

       ## UPDATED PROJECT DETAILS:
       - Project Type: ${projectType}
       - Files: ${projectFiles.join("\n")}
       - Code: ${fullCode.substring(0, 1000)}...
       - Repo URL: ${repoUrl || "Not specified"}

       ## CRITICAL UPDATE RULES:
       1. **PRESERVE CUSTOM CONTENT**: Keep ALL user-written sections, custom badges, personal introductions, custom licensing text, and any content that appears manually added.

       2. **UPDATE AUTO-GENERATED SECTIONS**: Only update sections that are clearly auto-generated:
          - Tech stack/technologies list
          - Installation instructions (if they reference old dependencies)
          - API endpoints documentation (if code changed)
          - Features list (if new features detected in code)
          - File structure (if significantly changed)

       3. **SMART DETECTION**: Identify custom vs auto-generated content by:
          - Looking for personal writing style or custom formatting
          - Checking if content matches actual code (outdated = auto-generated)
          - Preserving sections with unique badges, custom links, or personal notes

       4. **MERGE STRATEGY**:
          - If a section has both custom and auto-generated content, merge them intelligently
          - Keep custom introduction paragraphs
          - Update only the technical details (versions, dependencies, APIs)
          - Preserve custom examples and usage instructions

       5. **MAINTAIN STRUCTURE**: Keep the overall README structure and order of sections unless they're clearly outdated

       6. **NO EMOJIS**: Do not add any emojis when updating. If the existing README has emojis that the user added, keep them, but don't add new ones.

       7. **NATURAL TONE**: Write the Overview section naturally, focusing on what the project does, not the technologies used. Save tech stack details for the "Technologies Used" section.

        ${options.includeDiagrams === true ? `
        8. **DIAGRAMS / SYSTEM DESIGN**:
           - If the existing README does not have a System Architecture / Design section or diagrams, add them now.
           - Generate a high-level architecture diagram and place it in a new section (e.g., after Features).
           - Add detailed sequence or flowchart diagrams under key features in the Features section (aim for 2-4 feature diagrams total, e.g. auth flow, payment processing flow).
           - Follow all Mermaid syntax and styling guidelines in the system instructions.
        ` : ''}

        ${options.includeDiagrams === true ? '9' : '8'}. **DOKUGEN BADGE**: Always include this badge at the very bottom:
          [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://www.npmjs.com/package/dokugen)

       ## OUTPUT:
       Generate the UPDATED README that preserves custom content while refreshing auto-generated sections. Do NOT wrap in code blocks.`
      : `Generate a **high-quality, professional, and modern README.md that must impress recruiters and make them hire me** for a **${projectType}** project.
       ## Project Overview:
       The project includes the following files:
       ${projectFiles.join("\n")}

       ## Full Code Context:
       Below is the actual and compelete source code. So i believe you have 100% of the full code:
       ${fullCode}

       ## README Requirements:
        - **Title**:
           - Create a clear and professional title for the project. You can find the project title from the metadata files (e.g package.json, go.mod, etc). If you don't find it, come up with a reasonable name. Do NOT add any emojis to the title.

        - **Description**:
           - Write a short and engaging description of the project that will make it stand out and attract potential users and contributors.

        - **Installation**:
          ${
            options.includeSetup === true
              ? `
          - Clone the Repository:
           \`\`\`bash
           git clone ${repoUrl || "<repository-url>"}
           \`\`\`
          - Include step-by-step instructions for setting up the project locally.
          - Use bullet points and code blocks for clarity.
          `
              : "<!-- SKIP SECTION: User opted out of Installation Instructions. DO NOT ADD THIS SECTION. -->"
          }

        - **Usage**:
           - Include examples and screenshots if available. Check if there are screenshot files in the project (like demo.png, screenshot.png) and include them if found.
           - Add detailed usage instructions. Don't collapse them into expandable sections.

        - **Features**:
           - Create a list of key features with brief descriptions.
           ${
             options.includeDiagrams === true
               ? `- For at least 2-4 key features, add a dedicated Mermaid diagram (e.g. sequence diagram or flowchart) directly beneath the feature's description to visualize its workflow (e.g. auth flow, payment processing flow, session management, coupon validation). Follow the Mermaid syntax rules strictly.`
               : ""
           }

        ${
          options.includeDiagrams === true
            ? `- **System Architecture / Design**:
           - Include a high-level system design diagram using Mermaid (flowchart LR or TD) representing the overall architecture (clients, services, databases, external API, etc.) as described in the system instructions.`
            : ""
        }

        - **Technologies Used**:
           - Display a table or grid of technologies with links.

        ${
          options.includeApiDocs === true
            ? `
        - **API Documentation** (For Backend/Full-Stack Projects):
           - If this is a backend or full-stack project with API endpoints, document ALL endpoints:
           - Use this format for each endpoint:
             #### [HTTP METHOD] [ENDPOINT PATH]
             **Description**: [What this endpoint does]

             **Request**:
             \`\`\`json
             {
               "field": "value"
             }
             \`\`\`

             **Response**:
             \`\`\`json
             {
               "status": "success",
               "data": {}
             }
             \`\`\`

             **Errors**:
             - 400: [Error description]
             - 401: [Error description]
           - Include authentication requirements
           - Document request/response schemas
           - List all environment variables needed
          `
            : "<!-- SKIP SECTION: User opted out of API Documentation. DO NOT ADD THIS SECTION. -->"
        }

        - **Contributing**:
           ${
             options.includeContributionGuideLine === true
               ? `
           - Include guidelines for contributing to the project.
           - Use clean, professional formatting without emojis.
           `
               : "<!-- SKIP SECTION: User Opted out of contributions guidelines. DO NOT ADD THIS SECTION. -->"
           }

        - **License**:
           - Include a license section with a link. If the user does not have a LICENSE file in the project files, don't add a license link in the readme.

        - **Author Info**:
           - Create a clean author section with social media links.
           ${options.linkedinUrl ? `- LinkedIn: use this exact URL: ${options.linkedinUrl}` : "- LinkedIn: leave a placeholder [Your LinkedIn](https://linkedin.com/in/yourusername)"}
           ${options.twitterUrl ? `- X (Twitter): use this exact URL: ${options.twitterUrl}` : "- X (Twitter): leave a placeholder [@yourhandle](https://x.com/yourhandle)"}

        - **Badges**:
            - Add technology badges at the bottom of the README.

        - **Dokugen Badge**:
            - Always include this badge at the very bottom of the README:
              \`\`\`
       [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://www.npmjs.com/package/dokugen)
              \`\`\`

       ## Tone and Style:
       - Keep the README clean, professional, and mature.
       - NO EMOJIS - keep it professional and clean.
       - Use natural, conversational language that sounds human-written.
       - Focus on what the project does, not the technologies (save those for the "Technologies Used" section).

       ## Additional Requirements:
       - The README must sound like a human wrote it. Avoid AI-generated phrasing.
       - Write the Overview section naturally, explaining what the project does and what problem it solves.
       - Do NOT wrap the README in markdown code blocks (\`\`\`markdown or \`\`\`).

       ## Final Output:
       Generate the README.md content directly, without any additional explanations or wrapping.
       `;
}
