export function buildUserPrompt(
  formatTemplate: string | null | undefined,
  repoUrl: string | null | undefined,
  projectType: string,
  projectFiles: string[],
  fullCode: string,
  existingReadme: string | null | undefined,
  options: {
    includeSetup?: boolean;
    includeContributionGuideLine?: boolean;
    includeApiDocs?: boolean;
    includeDiagrams?: boolean;
    linkedinUrl?: string;
    twitterUrl?: string;
    isIncremental?: boolean;
    modifiedFiles?: string[];
  } = {}
): string {
  return formatTemplate
    ? `
      STRICTLY USE THIS TEMPLATE STRUCTURE:
     """
     ${formatTemplate}
     """

     INJECT THESE PROJECT DETAILS:
     - Repo URL: ${repoUrl || "Not specified"}
     - Project Type: ${projectType}
     - Main Files: ${projectFiles.slice(0, 10).join(", ")}...
     - Code Sample: ${fullCode.substring(0, 1000)}...

     RULES:
     1. PRESERVE ALL TEMPLATE SECTIONS IN ORDER
     2. REPLACE CONTENT BUT KEEP STYLING
     3. ADD THIS BADGE AT BOTTOM:
        [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://dokugen-readme.vercel.app)`
    : existingReadme
      ? `You are updating an existing README.md file. Your task is to INTELLIGENTLY UPDATE only the auto-generated sections while PRESERVING all custom content added by the user.

       ## EXISTING README CONTENT:
       """
       ${existingReadme}
       """

       ${options.isIncremental === true ? `
       ## INCREMENTAL UPDATE INFORMATION:
       - This is an incremental update request. The codebase was previously scanned and a README generated.
       - The 'Code' section below ONLY contains code for files that have been modified or added since the last generation:
         ${options.modifiedFiles ? options.modifiedFiles.map(f => `- ${f}`).join('\n') : '(modified files list not specified)'}
       - All other files listed in the project files list are completely unchanged.
       - Use these modified/new files to update relevant sections (such as new/changed API endpoints, new features, or setup changes), but preserve all other parts of the existing README as-is.
       ` : ''}

       ## UPDATED PROJECT DETAILS:
       - Project Type: ${projectType}
       - Files: ${projectFiles.join("\n")}
       - Code:
       ${fullCode}
       - Repo URL: ${repoUrl || "Not specified"}

       ## CRITICAL UPDATE RULES:
       1. **PRESERVE CUSTOM CONTENT**: Keep ALL user-written sections, custom badges, personal introductions, custom licensing text, and any content that appears manually added.

       2. **UPDATE AUTO-GENERATED SECTIONS**: Only update sections that are clearly auto-generated:
          - Tech stack/technologies list
          - Installation instructions (if they reference old dependencies)
          - API endpoints documentation (if code changed)
          - Features list (if new features detected in code)
          - File structure (if significantly changed)

       3. **SMART DETECTION**: Identify custom vs auto-generated content by:
          - Looking for personal writing style or custom formatting
          - Checking if content matches actual code (outdated = auto-generated)
          - Preserving sections with unique badges, custom links, or personal notes

       4. **MERGE STRATEGY**:
          - If a section has both custom and auto-generated content, merge them intelligently
          - Keep custom introduction paragraphs
          - Update only the technical details (versions, dependencies, APIs)
          - Preserve custom examples and usage instructions

        5. **MAINTAIN STRUCTURE**: Keep the overall README structure and order of sections unless they're clearly outdated.

        6. **NO DUPLICATIONS**: Do NOT duplicate sections, paragraphs, or list items. If you add a code block or example to an existing step, replace the old placeholder step cleanly. Do not repeat the step text before and after the code block.

        7. **MARKDOWN LIST NESTING**: When adding code blocks under numbered/bulleted steps, ensure they are correctly indented (e.g. 2 or 4 spaces) so they nest under the active list item. Do not break the list item text into two separate parent blocks.

        8. **ACCURATE CLI COMMANDS & ENDPOINTS**: Carefully read the project source code, routes, and package.json to output real, matching commands, endpoints, and flags. (e.g. if the route is /h/:id, do not write /webhook/:id. If the package name is @hooklens/cli, do not invent a different command name).

        9. **NO EMOJIS**: Do not add any emojis when updating. If the existing README has emojis that the user added, keep them, but don't add new ones.

        10. **NATURAL TONE**: Write the Overview section naturally, focusing on what the project does, not the technologies used. Save tech stack details for the "Technologies Used" section.

        ${options.includeDiagrams === true ? `
        11. **DIAGRAMS / SYSTEM DESIGN**:
           - If the existing README does not have a System Architecture / Design section or diagrams, add them now.
           - Generate a high-level architecture diagram and place it in a new section (e.g., after Features).
           - Add detailed sequence or flowchart diagrams under key features in the Features section (aim for 2-4 feature diagrams total, e.g. auth flow, payment processing flow).
           - Follow all Mermaid syntax and styling guidelines in the system instructions.
        ` : ''}

        ${options.includeDiagrams === true ? '12' : '11'}. **DOKUGEN BADGE**: Always include this badge at the very bottom:
          [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://dokugen-readme.vercel.app)

       ## OUTPUT:
       Generate the UPDATED README that preserves custom content while refreshing auto-generated sections. Do NOT wrap in code blocks.`
      : `Generate a **high-quality, professional, and modern README.md that must impress recruiters and make them hire me** for a **${projectType}** project.
       ## Project Overview:
       The project includes the following files:
       ${projectFiles.join("\n")}

       ## Full Code Context:
       Below is the actual and compelete source code. So i believe you have 100% of the full code:
       ${fullCode}

       ## README Requirements:
        - **Title**:
           - Create a clear and professional title for the project. You can find the project title from the metadata files (e.g package.json, go.mod, etc). If you don't find it, come up with a reasonable name. Do NOT add any emojis to the title.

        - **Description**:
           - Write a short and engaging description of the project that will make it stand out and attract potential users and contributors.

        - **Installation**:
          ${
            options.includeSetup === true
              ? `
          - Clone the Repository:
           \`\`\`bash
           git clone ${repoUrl || "<repository-url>"}
           \`\`\`
          - Include step-by-step instructions for setting up the project locally.
          - Use bullet points and code blocks for clarity.
          `
              : "<!-- SKIP SECTION: User opted out of Installation Instructions. DO NOT ADD THIS SECTION. -->"
          }

        - **Usage**:
           - Include examples and screenshots if available. Check if there are screenshot files in the project (like demo.png, screenshot.png) and include them if found.
           - Add detailed usage instructions. Don't collapse them into expandable sections.
           - CRITICAL: If you reference an example with phrases like "like this:", "for example:", or "it will look something like this:", you MUST immediately follow it with an actual code block or example. NEVER write a lead-in phrase and leave it with nothing after it. If you cannot infer a realistic example from the code, omit the lead-in phrase entirely.
           - For CLI tools or relay commands, infer a realistic example from the project code (e.g. package name, binary name, flags) and show it in a bash code block.

        - **Features**:
           - Create a list of key features with brief descriptions.
           ${
             options.includeDiagrams === true
               ? `- For at least 2-4 key features, add a dedicated Mermaid diagram (e.g. sequence diagram or flowchart) directly beneath the feature's description to visualize its workflow (e.g. auth flow, payment processing flow, session management, coupon validation). Follow the Mermaid syntax rules strictly.`
               : ""
           }

        ${
          options.includeDiagrams === true
            ? `- **System Architecture / Design**:
           - Include a high-level system design diagram using Mermaid (flowchart LR or TD) representing the overall architecture (clients, services, databases, external API, etc.) as described in the system instructions.`
            : ""
        }

        - **Technologies Used**:
           - Display a table or grid of technologies with links.

        ${
          options.includeApiDocs === true
            ? `
        - **API Documentation** (For Backend/Full-Stack Projects):
           - If this is a backend or full-stack project with API endpoints, document ALL endpoints:
           - Use this format for each endpoint:
             #### [HTTP METHOD] [ENDPOINT PATH]
             **Description**: [What this endpoint does]

             **Request**:
             \`\`\`json
             {
               "field": "value"
             }
             \`\`\`

             **Response**:
             \`\`\`json
             {
               "status": "success",
               "data": {}
             }
             \`\`\`

             **Errors**:
             - 400: [Error description]
             - 401: [Error description]
           - Include authentication requirements
           - Document request/response schemas
           - List all environment variables needed
          `
            : "<!-- SKIP SECTION: User opted out of API Documentation. DO NOT ADD THIS SECTION. -->"
        }

        - **Contributing**:
           ${
             options.includeContributionGuideLine === true
               ? `
           - Include a short Contributing section.
           - If a CONTRIBUTION.md, CONTRIBUTING.md, or similar file exists in the project files list, link to it using the full GitHub blob URL format: \`[Contribution Guide](${repoUrl ? repoUrl.replace(/\.git$/, "") + "/blob/main/CONTRIBUTION.md" : "https://github.com/<owner>/<repo>/blob/main/CONTRIBUTION.md"})\`. NEVER use a relative path like \`(CONTRIBUTION.md)\` or \`(./CONTRIBUTING.md)\`.
           - Use clean, professional formatting without emojis.
           `
               : "<!-- SKIP SECTION: User Opted out of contributions guidelines. DO NOT ADD THIS SECTION. -->"
           }

         - **License**:
            - CAREFULLY scan the project files list for ANY file named LICENSE, LICENSE.md, LICENSE.txt, COPYING, or similar. If found, identify the license type by reading the license file content in the code context (e.g. MIT, Apache 2.0, GPL-3.0, ISC) and write the License section explicitly naming the license type.
            - Link to the LICENSE file using the full GitHub blob URL. If the repo URL is "${repoUrl || "https://github.com/<owner>/<repo>"}", the link must be: \`[LICENSE](${repoUrl ? repoUrl.replace(/\.git$/, "") + "/blob/main/LICENSE" : "https://github.com/<owner>/<repo>/blob/main/LICENSE"})\`
            - NEVER use a relative path like \`[LICENSE](LICENSE)\` or \`[LICENSE](./LICENSE)\`. Always use the full blob URL.
            - Do NOT skip this section if a LICENSE file exists. Do NOT write vague filler text like "please refer to the repository for licensing details".
            - If absolutely no LICENSE file is found anywhere in the project files list, omit the License section entirely.

         - **Author Info**:
            - Create a clean author section with social media links. Each social link MUST be on its own separate line/bullet point — NEVER combine LinkedIn and X on the same line.
            ${options.linkedinUrl ? `- LinkedIn: Use this exact URL: ${options.linkedinUrl}. Do NOT write a placeholder link if this URL is provided.` : "- LinkedIn: Do NOT write any LinkedIn link, text, list item, or placeholder under Author Info. Omit it completely."}
            ${options.twitterUrl ? `- X (Twitter): Use this exact URL: ${options.twitterUrl}. Do NOT write a placeholder link if this URL is provided.` : "- X (Twitter): Do NOT write any X/Twitter link, text, list item, or placeholder under Author Info. Omit it completely."}
            - CRITICAL: If you know a social handle (e.g. @onyx_doe), the URL must match exactly (e.g. https://x.com/onyx_doe). NEVER use a placeholder URL like yourhandle or yourusername when you already have the real handle. Do NOT write any placeholders or generic templates for accounts that are omitted.

        - **Badges**:
           - Add technology badges at the bottom of the README using shield.io image badge format.
           - CORRECT format: [![TypeScript](https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white)](https://www.typescriptlang.org/)
           - WRONG format: [TypeScript](https://www.typescriptlang.org/) — plain markdown links are NOT badges and must never be used for the badges section.

        - **Dokugen Badge**:
            - Always include this badge at the very bottom of the README:
              \`\`\`
       [![Readme was generated by Dokugen](https://img.shields.io/badge/Readme%20was%20generated%20by-Dokugen-brightgreen)](https://dokugen-readme.vercel.app)
              \`\`\`

       ## Tone and Style:
       - Keep the README clean, professional, and mature.
       - NO EMOJIS - keep it professional and clean.
       - Use natural, conversational language that sounds human-written.
       - Focus on what the project does, not the technologies (save those for the "Technologies Used" section).

       ## Additional Requirements:
        - The README must sound like a human wrote it. Avoid AI-generated phrasing.
        - Write the Overview section naturally, explaining what the project does and what problem it solves.
        - Do NOT wrap the README in markdown code blocks (\`\`\`markdown or \`\`\`).
        - Do NOT indent regular paragraphs or explanation text under lists with 4 or more spaces. Keep they aligned to the margin (0 spaces) or indent with exactly 2 spaces if nesting. 4 spaces will trigger Markdown code-block mode and break all your link renderings.
        - **INTERNAL FILE LINKS — BLOB URLS ONLY**: When linking to any file that lives inside the repository (LICENSE, CONTRIBUTION.md, CONTRIBUTING.md, CODE_OF_CONDUCT.md, CHANGELOG.md, etc.), ALWAYS use the full GitHub blob URL (e.g. \`https://github.com/owner/repo/blob/main/LICENSE\`). NEVER use relative paths like \`(LICENSE)\` or \`(./LICENSE)\`.

       ## Final Output:
       Generate the README.md content directly, without any additional explanations or wrapping.
       `;
}
