import os
import sys
from rich.console import Console
from dokugen import utils
from dokugen.project_detect import detect_project_type
from dokugen.commands.generate import generate_readme_remote, ask_yes_no, DOKUGEN_BANNER

console = Console()


def cmd_update(args):
    if not utils.is_git_repository():
        console.print("[red]Opps... No Git repository found. Please navigate to a project directory that has a Git repository, or initialize one using 'git init'.[/red]")
        sys.exit(1)

    utils.check_and_update()
    console.print(DOKUGEN_BANNER, style="#000080")

    project_dir = os.getcwd()
    readme_path = os.path.join(project_dir, "README.md")

    if not os.path.exists(readme_path):
        console.print("[red]No README.md found. Use 'dokugen generate' to create one first.[/red]")
        sys.exit(1)

    with utils.create_spinner("Checking internet..."):
        has_connection = utils.check_internet_connection()

    if not has_connection:
        raw_username = utils.get_user_info().get("username", "Unknown")
        import re
        username = re.sub(r'\d+', '', raw_username)
        console.print(f"[red]Opps... {username} kindly check your device or pc internet connection and try again.[/red]")
        return

    try:
        utils.backup_readme(readme_path)

        template_url = getattr(args, "template", None)

        if template_url and "github.com" not in template_url:
            console.print("[red]Invalid GitHub URL. Use format: https://github.com/user/repo/blob/main/README.md[/red]")
            sys.exit(1)

        with open(readme_path, "r", encoding="utf-8") as f:
            existing_content = f.read()

        has_markers = "<!-- DOKUGEN:" in existing_content or "[![Readme was generated by Dokugen]" in existing_content

        if not has_markers:
            console.print("[yellow]This README doesn't appear to be generated by Dokugen.[/yellow]")
            project_name = os.path.basename(project_dir)
            ans = ask_yes_no(f"Do you want to regenerate the entire {project_name} README?")

            if ans == "yes":
                project_type = detect_project_type(project_dir)
                with utils.create_spinner("Scanning project files..."):
                    project_files = utils.scan_files(project_dir)
                console.print(f"[yellow]Found: {len(project_files)} files in the project[/yellow]")

                generate_readme_remote(project_type, project_files, project_dir, None, template_url)
                console.print("[green]README.md regenerated successfully![/green]")
                return
            else:
                console.print("[yellow]Update cancelled.[/yellow]")
                utils.restore_readme()
                return

        console.print("[blue]Analyzing README structure...[/blue]")
        project_type = detect_project_type(project_dir)

        with utils.create_spinner("Scanning project files..."):
            project_files = utils.scan_files(project_dir)

        console.print(f"[yellow]Found: {len(project_files)} files in the project[/yellow]")
        console.print(f"[blue]Detected project type: {project_type}[/blue]")
        console.print("[blue]Updating auto-generated sections...[/blue]")

        generate_readme_remote(project_type, project_files, project_dir, existing_content, template_url)
        console.print("[green]README.md updated successfully! Custom sections preserved.[/green]")

    except (Exception, KeyboardInterrupt) as e:
        if isinstance(e, KeyboardInterrupt):
            console.print("[yellow]\nProcess interrupted. Restoring backup...[/yellow]")
        else:
            console.print(f"[red]Error updating README: {e}[/red]")
        utils.restore_readme()
        sys.exit(1)


def register_update_parser(subparsers):
    project_name = os.path.basename(os.getcwd())
    up_parser = subparsers.add_parser("update", help=f"Update auto-generated sections of {project_name} README while preserving custom content")
    up_parser.add_argument(
        "--template",
        help="use a custom GitHub repo readme file as a template",
    )
